// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

// @formatter:off

#![allow(dead_code)]

use wasmlib::*;

use crate::*;

pub const IDX_PARAM_INSTRUCTION: usize = 0;
pub const IDX_PARAM_MACHINE_ID:  usize = 1;
pub const IDX_PARAM_OWNER:       usize = 2;
pub const IDX_PARAM_RESPONSE:    usize = 3;
pub const IDX_PARAM_TASK_ID:     usize = 4;
pub const IDX_RESULT_OWNER:      usize = 5;
pub const IDX_RESULT_STATUS:     usize = 6;
pub const IDX_STATE_OWNER:       usize = 7;
pub const IDX_STATE_TASKS:       usize = 8;

pub const KEY_MAP_LEN: usize = 9;

pub const KEY_MAP: [&str; KEY_MAP_LEN] = [
    PARAM_INSTRUCTION,
    PARAM_MACHINE_ID,
    PARAM_OWNER,
    PARAM_RESPONSE,
    PARAM_TASK_ID,
    RESULT_OWNER,
    RESULT_STATUS,
    STATE_OWNER,
    STATE_TASKS,
];

pub static mut IDX_MAP: [Key32; KEY_MAP_LEN] = [Key32(0); KEY_MAP_LEN];

pub fn idx_map(idx: usize) -> Key32 {
    unsafe {
        IDX_MAP[idx]
    }
}

// @formatter:on
