// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

#![allow(dead_code)]
#![allow(unused_imports)]

use wasmlib::*;
use wasmlib::host::*;

use crate::*;
use crate::keys::*;

#[derive(Clone, Copy)]
pub struct ImmutableInitParams {
    pub(crate) id: i32,
}

impl ImmutableInitParams {
    pub fn owner(&self) -> ScImmutableAgentID {
        ScImmutableAgentID::new(self.id, idx_map(IDX_PARAM_OWNER))
    }
}

#[derive(Clone, Copy)]
pub struct MutableInitParams {
    pub(crate) id: i32,
}

impl MutableInitParams {
    pub fn owner(&self) -> ScMutableAgentID {
        ScMutableAgentID::new(self.id, idx_map(IDX_PARAM_OWNER))
    }
}

#[derive(Clone, Copy)]
pub struct ImmutableIssuerConfirmResultParams {
    pub(crate) id: i32,
}

impl ImmutableIssuerConfirmResultParams {
    pub fn task_id(&self) -> ScImmutableInt32 {
        ScImmutableInt32::new(self.id, idx_map(IDX_PARAM_TASK_ID))
    }
}

#[derive(Clone, Copy)]
pub struct MutableIssuerConfirmResultParams {
    pub(crate) id: i32,
}

impl MutableIssuerConfirmResultParams {
    pub fn task_id(&self) -> ScMutableInt32 {
        ScMutableInt32::new(self.id, idx_map(IDX_PARAM_TASK_ID))
    }
}

#[derive(Clone, Copy)]
pub struct ImmutableIssuerRejectResultParams {
    pub(crate) id: i32,
}

impl ImmutableIssuerRejectResultParams {
    pub fn task_id(&self) -> ScImmutableInt32 {
        ScImmutableInt32::new(self.id, idx_map(IDX_PARAM_TASK_ID))
    }
}

#[derive(Clone, Copy)]
pub struct MutableIssuerRejectResultParams {
    pub(crate) id: i32,
}

impl MutableIssuerRejectResultParams {
    pub fn task_id(&self) -> ScMutableInt32 {
        ScMutableInt32::new(self.id, idx_map(IDX_PARAM_TASK_ID))
    }
}

#[derive(Clone, Copy)]
pub struct ImmutableIssuerRequestTaskParams {
    pub(crate) id: i32,
}

impl ImmutableIssuerRequestTaskParams {
    pub fn instruction(&self) -> ScImmutableString {
        ScImmutableString::new(self.id, idx_map(IDX_PARAM_INSTRUCTION))
    }

    pub fn machine_id(&self) -> ScImmutableAgentID {
        ScImmutableAgentID::new(self.id, idx_map(IDX_PARAM_MACHINE_ID))
    }
}

#[derive(Clone, Copy)]
pub struct MutableIssuerRequestTaskParams {
    pub(crate) id: i32,
}

impl MutableIssuerRequestTaskParams {
    pub fn instruction(&self) -> ScMutableString {
        ScMutableString::new(self.id, idx_map(IDX_PARAM_INSTRUCTION))
    }

    pub fn machine_id(&self) -> ScMutableAgentID {
        ScMutableAgentID::new(self.id, idx_map(IDX_PARAM_MACHINE_ID))
    }
}

#[derive(Clone, Copy)]
pub struct ImmutableMachineFinnishTaskParams {
    pub(crate) id: i32,
}

impl ImmutableMachineFinnishTaskParams {
    pub fn task_id(&self) -> ScImmutableInt32 {
        ScImmutableInt32::new(self.id, idx_map(IDX_PARAM_TASK_ID))
    }
}

#[derive(Clone, Copy)]
pub struct MutableMachineFinnishTaskParams {
    pub(crate) id: i32,
}

impl MutableMachineFinnishTaskParams {
    pub fn task_id(&self) -> ScMutableInt32 {
        ScMutableInt32::new(self.id, idx_map(IDX_PARAM_TASK_ID))
    }
}

#[derive(Clone, Copy)]
pub struct ImmutableMachineQuitTaskParams {
    pub(crate) id: i32,
}

impl ImmutableMachineQuitTaskParams {
    pub fn task_id(&self) -> ScImmutableInt32 {
        ScImmutableInt32::new(self.id, idx_map(IDX_PARAM_TASK_ID))
    }
}

#[derive(Clone, Copy)]
pub struct MutableMachineQuitTaskParams {
    pub(crate) id: i32,
}

impl MutableMachineQuitTaskParams {
    pub fn task_id(&self) -> ScMutableInt32 {
        ScMutableInt32::new(self.id, idx_map(IDX_PARAM_TASK_ID))
    }
}

#[derive(Clone, Copy)]
pub struct ImmutableMachineResponseParams {
    pub(crate) id: i32,
}

impl ImmutableMachineResponseParams {
    pub fn response(&self) -> ScImmutableInt16 {
        ScImmutableInt16::new(self.id, idx_map(IDX_PARAM_RESPONSE))
    }

    pub fn task_id(&self) -> ScImmutableInt32 {
        ScImmutableInt32::new(self.id, idx_map(IDX_PARAM_TASK_ID))
    }
}

#[derive(Clone, Copy)]
pub struct MutableMachineResponseParams {
    pub(crate) id: i32,
}

impl MutableMachineResponseParams {
    pub fn response(&self) -> ScMutableInt16 {
        ScMutableInt16::new(self.id, idx_map(IDX_PARAM_RESPONSE))
    }

    pub fn task_id(&self) -> ScMutableInt32 {
        ScMutableInt32::new(self.id, idx_map(IDX_PARAM_TASK_ID))
    }
}

#[derive(Clone, Copy)]
pub struct ImmutableGetTaskParams {
    pub(crate) id: i32,
}

impl ImmutableGetTaskParams {
    pub fn task_id(&self) -> ScImmutableInt32 {
        ScImmutableInt32::new(self.id, idx_map(IDX_PARAM_TASK_ID))
    }
}

#[derive(Clone, Copy)]
pub struct MutableGetTaskParams {
    pub(crate) id: i32,
}

impl MutableGetTaskParams {
    pub fn task_id(&self) -> ScMutableInt32 {
        ScMutableInt32::new(self.id, idx_map(IDX_PARAM_TASK_ID))
    }
}
