// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

// @formatter:off

#![allow(dead_code)]

use wasmlib::*;

pub const SC_NAME:        &str = "test";
pub const SC_DESCRIPTION: &str = "test description";
pub const HSC_NAME:       ScHname = ScHname(0x36208b92);

pub const PARAM_DESCRIPTION: &str = "description";

pub const STATE_TEST_STRUCTS: &str = "testStructs";

pub const FUNC_ADD_TEST_STRUCT: &str = "addTestStruct";
pub const FUNC_CLEAR_ALL:       &str = "clearAll";

pub const HFUNC_ADD_TEST_STRUCT: ScHname = ScHname(0x9dbe9a07);
pub const HFUNC_CLEAR_ALL:       ScHname = ScHname(0x7c3a13e7);

// @formatter:on
