// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

// @formatter:off

#![allow(dead_code)]

use std::ptr;

use wasmlib::*;

use crate::consts::*;
use crate::params::*;
use crate::results::*;

pub struct AddTestStructCall {
    pub func:   ScFunc,
    pub params: MutableAddTestStructParams,
}

pub struct ClearAllCall {
    pub func: ScFunc,
}

pub struct ScFuncs {
}

impl ScFuncs {
    pub fn add_test_struct(_ctx: & dyn ScFuncCallContext) -> AddTestStructCall {
        let mut f = AddTestStructCall {
            func:   ScFunc::new(HSC_NAME, HFUNC_ADD_TEST_STRUCT),
            params: MutableAddTestStructParams { id: 0 },
        };
        f.func.set_ptrs(&mut f.params.id, ptr::null_mut());
        f
    }
    pub fn clear_all(_ctx: & dyn ScFuncCallContext) -> ClearAllCall {
        ClearAllCall {
            func: ScFunc::new(HSC_NAME, HFUNC_CLEAR_ALL),
        }
    }
}

// @formatter:on
