// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

// @formatter:off

#![allow(dead_code)]

use wasmlib::*;

use crate::*;

pub(crate) const IDX_PARAM_DESCRIPTION:  usize = 0;
pub(crate) const IDX_STATE_TEST_STRUCTS: usize = 1;

pub const KEY_MAP_LEN: usize = 2;

pub const KEY_MAP: [&str; KEY_MAP_LEN] = [
    PARAM_DESCRIPTION,
    STATE_TEST_STRUCTS,
];

pub static mut IDX_MAP: [Key32; KEY_MAP_LEN] = [Key32(0); KEY_MAP_LEN];

pub fn idx_map(idx: usize) -> Key32 {
    unsafe {
        IDX_MAP[idx]
    }
}

// @formatter:on
